### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by amitmerchant1990** [feross/electron-workshop#1]
Hey @feross 

This is a great step for getting electron to more audience reach. The content that you wrote is great. As you have taken Markdown as your example, you can also include my app [Markdownify](https://github.com/amitmerchant1990/electron-markdownify) which I have built using Electron only. The app is quite relevant to the workshop you made. So, the audience will get to know how the ultimate app would look and work like.

Hope for your reply soon!

Thanks!

**Comment by feross** [comment]
If you send a PR that adds a small note about your app, I'll merge it.
