### ISSUE TITLE
Save menu item saves HTML with content "undefined"

### ISSUE THREAD

**Issue by jcansdale** [feross/electron-workshop#12]
``` js
      {
        label: 'Save',
        accelerator: 'CmdOrCtrl+S',
        click () { saveFile() }
      }
```

I guess `saveFile(...)` somehow needs to grab the content from `renderer.js`.

**Comment by feross** [comment]
That's right. Thanks for finding this bug. I'll update the workshop.

**Comment by feross** [comment]
Okay, I updated the workshop to fix this issue. Thanks @jcansdale!
