### ISSUE TITLE
Don't use jQuery

### ISSUE THREAD

**Issue by thlorenz** [feross/electron-workshop#2]
You know exactly what query selectors electron supports (it's chromium), pulling in huge jQuery makes no sense [here](https://github.com/feross/electron-workshop/blob/master/lib-solution/renderer.js#L8) IMO.

Additionally this workshop could serve to introduce folks to learn about those document query selectors, instead it teaches them the ways of the 90s :P

Since I already know what you're gonna say I'm gonna preempt with the info that I got no bandwidth for PRs unfortunately.

**Comment by feross** [comment]
Thanks to @emilbayes this is done now! Sorry it took me so long to merge. I've been taking a little break from open source for a while so I don't burn out. 👍 Agree with you that jQuery isn't necessary anymore.
