### ISSUE TITLE
Error in postinstall, installing electron

### ISSUE THREAD

**Issue by YerkoPalma** [feross/electron-workshop#4]
Trying to install electron I have the following error. I know this isn't exactly related with this workshop, because I have not even started it. Is this an electron bug? should be reported there? Or might be related with node? I use nvm to manage node versions, the following output is with `node v6.9.x`

```
> electron@1.4.4 postinstall /home/yerko/.nvm/versions/node/v6.0.0/lib/node_modules/electron
> node install.js

Downloading electron-v1.4.4-linux-x64.zip
[============================================>] 100.0% of 43.28 MB (1.25 MB/s)
/home/yerko/.nvm/versions/node/v6.0.0/lib/node_modules/electron/install.js:22
  throw err
  ^

Error
    at ChecksumParseError.Error (native)
    at new ChecksumParseError (/home/yerko/.nvm/versions/node/v6.0.0/lib/node_modules/electron/node_modules/sumchecker/build.js:68:127)
    at /home/yerko/.nvm/versions/node/v6.0.0/lib/node_modules/electron/node_modules/sumchecker/build.js:123:20
    at Array.forEach (native)
    at /home/yerko/.nvm/versions/node/v6.0.0/lib/node_modules/electron/node_modules/sumchecker/build.js:118:38
    at ChecksumValidator.parseChecksumFile (/home/yerko/.nvm/versions/node/v6.0.0/lib/node_modules/electron/node_modules/sumchecker/build.js:114:14)
```

Now, the purpose for this issue is that, if this is a node/electron bug, it should be IMO stated in this tutorial.
Thanks for reading.

**Comment by feross** [comment]
This looks like a download error. The checksum is failing to validate, which means that Electron got corrupted while it was being downloaded. I suggest trying again. If you continue to get this error, then try switching networks or open an issue on Electron.
